# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e57e4d892e863bcb15d7d752a9d2063d13f294b7bc86d142183f23d1e7abb72275705c1db93dc7c19f9eb98be810fdf72f66272ae072cd87896fcf2b3007a32

test:
  secret_key_base: 729a476b00229dc2c42d4fa49d1242142e6795bfe2a18a572fd24d3b5f4377c6e55bdcb727eb47f080423e2bd28ad56ac4ccb9c3a4c9b4a9cbf12427aefb2a27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
