# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d54bcfdb527e76ce8d1f52c5c32475a3fdd8f6843004323e38be13fc67cf2a50a11f39beff552ded89967ab6faa0fe0955e8bc6db7589627025ae2f72f332ba1

test:
  secret_key_base: 70fb8c426a5b8dd3c99b0165536208422bd670540e7f5fafd522c88ebb793b8b3bec8288b6c2b940bf95b291b435d6617a388df4bffd7ac2fb567b8d2c9b3827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
